In [1]:
# ==========================
# Import Required Libraries
# ==========================

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings('ignore')

# Display all columns
pd.set_option('display.max_columns', None)

print("Libraries Imported Successfully!")

Libraries Imported Successfully!

In [6]:
# ==========================
# Load Datasets
# ==========================

train = pd.read_csv("train.csv")
features = pd.read_csv("features.csv")
stores = pd.read_csv("stores.csv")

print("Datasets Loaded Successfully!")

Datasets Loaded Successfully!

In [7]:
# ==========================
# Display First Five Rows
# ==========================

print("TRAIN DATA")
display(train.head())

print("\nFEATURES DATA")
display(features.head())

print("\nSTORES DATA")
display(stores.head())

TRAIN DATA

   Store  Dept        Date  Weekly_Sales  IsHoliday
0      1     1  2010-02-05      24924.50      False
1      1     1  2010-02-12      46039.49       True
2      1     1  2010-02-19      41595.55      False
3      1     1  2010-02-26      19403.54      False
4      1     1  2010-03-05      21827.90      False

FEATURES DATA

,Store,Date,Temperature,Fuel_Price,MarkDown1,MarkDown2,MarkDown3,MarkDown4,MarkDown5,CPI,Unemployment,IsHoliday
0,1,2010-02-05,42.31,2.572,NaN,NaN,NaN,NaN,NaN,211.096358,8.106,False
1,1,2010-02-12,38.51,2.548,NaN,NaN,NaN,NaN,NaN,211.242170,8.106,True
2,1,2010-02-19,39.93,2.514,NaN,NaN,NaN,NaN,NaN,211.289143,8.106,False
3,1,2010-02-26,46.63,2.561,NaN,NaN,NaN,NaN,NaN,211.319643,8.106,False
4,1,2010-03-05,46.50,2.625,NaN,NaN,NaN,NaN,NaN,211.350143,8.106,False

STORES DATA

   Store Type    Size
0      1    A  151315
1      2    A  202307
2      3    B   37392
3      4    A  205863
4      5    B   34875

In [8]:
# ==========================
# Shape of Datasets
# ==========================

print("Train Shape :", train.shape)
print("Features Shape :", features.shape)
print("Stores Shape :", stores.shape)

Train Shape : (421570, 5)
Features Shape : (8190, 12)
Stores Shape : (45, 3)

In [9]:
# ==========================
# Column Names
# ==========================

print("TRAIN COLUMNS")
print(train.columns)

print("\nFEATURES COLUMNS")
print(features.columns)

print("\nSTORES COLUMNS")
print(stores.columns)

TRAIN COLUMNS
Index(['Store', 'Dept', 'Date', 'Weekly_Sales', 'IsHoliday'], dtype='object')

FEATURES COLUMNS
Index(['Store', 'Date', 'Temperature', 'Fuel_Price', 'MarkDown1', 'MarkDown2',
       'MarkDown3', 'MarkDown4', 'MarkDown5', 'CPI', 'Unemployment',
       'IsHoliday'],
      dtype='object')

STORES COLUMNS
Index(['Store', 'Type', 'Size'], dtype='object')

In [10]:
# ==========================
# Data Types
# ==========================

print(train.dtypes)

print(features.dtypes)

print(stores.dtypes)

Store             int64
Dept              int64
Date             object
Weekly_Sales    float64
IsHoliday          bool
dtype: object
Store             int64
Date             object
Temperature     float64
Fuel_Price      float64
MarkDown1       float64
MarkDown2       float64
MarkDown3       float64
MarkDown4       float64
MarkDown5       float64
CPI             float64
Unemployment    float64
IsHoliday          bool
dtype: object
Store     int64
Type     object
Size      int64
dtype: object

In [11]:
# ==========================
# Dataset Information
# ==========================

print("TRAIN DATASET")
train.info()

print("\nFEATURES DATASET")
features.info()

print("\nSTORES DATASET")
stores.info()

TRAIN DATASET
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 421570 entries, 0 to 421569
Data columns (total 5 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   Store         421570 non-null  int64
 1   Dept          421570 non-null  int64
 2   Date          421570 non-null  object
 3   Weekly_Sales  421570 non-null  float64
 4   IsHoliday     421570 non-null  bool
dtypes: bool(1), float64(1), int64(2), object(1)
memory usage: 13.3+ MB

FEATURES DATASET
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8190 entries, 0 to 8189
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Store         8190 non-null   int64
 1   Date          8190 non-null   object
 2   Temperature   8190 non-null   float64
 3   Fuel_Price    8190 non-null   float64
 4   MarkDown1     4032 non-null   float64
 5   MarkDown2     2921 non-null   float64
 6   MarkDown3     3613 non-null   float64
 7   MarkDown4     3464 non-null   float64
 8   MarkDown5     4050 non-null   float64
 9   CPI           7605 non-null   float64
 10  Unemployment  7605 non-null   float64
 11  IsHoliday     8190 non-null   bool
dtypes: bool(1), float64(9), int64(1), object(1)
memory usage: 712.0+ KB

STORES DATASET
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45 entries, 0 to 44
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Store   45 non-null     int64
 1   Type    45 non-null     object
 2   Size    45 non-null     int64
dtypes: int64(2), object(1)
memory usage: 1.2+ KB

In [14]:
# ==========================
# Statistical Summary
# ==========================

train.describe()

               Store           Dept   Weekly_Sales
count  421570.000000  421570.000000  421570.000000
mean       22.200546      44.260317   15981.258123
std        12.785297      30.492054   22711.183519
min         1.000000       1.000000   -4988.940000
25%        11.000000      18.000000    2079.650000
50%        22.000000      37.000000    7612.030000
75%        33.000000      74.000000   20205.852500
max        45.000000      99.000000  693099.360000

In [15]:
features.describe()

,Store,Temperature,Fuel_Price,MarkDown1,MarkDown2,MarkDown3,MarkDown4,MarkDown5,CPI,Unemployment
count,8190.000000,8190.000000,8190.000000,4032.000000,2921.000000,3613.000000,3464.000000,4050.000000,7605.000000,7605.000000
mean,23.000000,59.356198,3.405992,7032.371786,3384.176594,1760.100180,3292.935886,4132.216422,172.460809,7.826821
std,12.987966,18.678607,0.431337,9262.747448,8793.583016,11276.462208,6792.329861,13086.690278,39.738346,1.877259
min,1.000000,-7.290000,2.472000,-2781.450000,-265.760000,-179.260000,0.220000,-185.170000,126.064000,3.684000
25%,12.000000,45.902500,3.041000,1577.532500,68.880000,6.600000,304.687500,1440.827500,132.364839,6.634000
50%,23.000000,60.710000,3.513000,4743.580000,364.570000,36.260000,1176.425000,2727.135000,182.764003,7.806000
75%,34.000000,73.880000,3.743000,8923.310000,2153.350000,163.150000,3310.007500,4832.555000,213.932412,8.567000
max,45.000000,101.950000,4.468000,103184.980000,104519.540000,149483.310000,67474.850000,771448.100000,228.976456,14.313000

In [16]:
stores.describe()

           Store           Size
count  45.000000      45.000000
mean   23.000000  130287.600000
std    13.133926   63825.271991
min     1.000000   34875.000000
25%    12.000000   70713.000000
50%    23.000000  126512.000000
75%    34.000000  202307.000000
max    45.000000  219622.000000

In [17]:
# ==========================
# Missing Values
# ==========================

print("TRAIN")
print(train.isnull().sum())

print("\nFEATURES")
print(features.isnull().sum())

print("\nSTORES")
print(stores.isnull().sum())

TRAIN
Store           0
Dept            0
Date            0
Weekly_Sales    0
IsHoliday       0
dtype: int64

FEATURES
Store              0
Date               0
Temperature        0
Fuel_Price         0
MarkDown1       4158
MarkDown2       5269
MarkDown3       4577
MarkDown4       4726
MarkDown5       4140
CPI              585
Unemployment     585
IsHoliday          0
dtype: int64

STORES
Store    0
Type     0
Size     0
dtype: int64

In [18]:
# ==========================
# Missing Value Percentage
# ==========================

missing = features.isnull().sum()

missing_percent = (missing / len(features)) * 100

missing_df = pd.DataFrame({
    "Missing Values": missing,
    "Percentage": missing_percent
})

missing_df.sort_values(by="Percentage", ascending=False)

              Missing Values  Percentage
MarkDown2               5269   64.334554
MarkDown4               4726   57.704518
MarkDown3               4577   55.885226
MarkDown1               4158   50.769231
MarkDown5               4140   50.549451
CPI                      585    7.142857
Unemployment             585    7.142857
Store                      0    0.000000
Fuel_Price                 0    0.000000
Temperature                0    0.000000
Date                       0    0.000000
IsHoliday                  0    0.000000

In [21]:
# ==========================
# Fill Missing Values
# ==========================

markdown_cols = [
    'MarkDown1',
    'MarkDown2',
    'MarkDown3',
    'MarkDown4',
    'MarkDown5'
]

features[markdown_cols] = features[markdown_cols].fillna(0)
features['CPI'] = features.groupby('Store')['CPI'].ffill()
features['Unemployment'] = features.groupby('Store')['Unemployment'].ffill()

features.isnull().sum()

Store           0
Date            0
Temperature     0
Fuel_Price      0
MarkDown1       0
MarkDown2       0
MarkDown3       0
MarkDown4       0
MarkDown5       0
CPI             0
Unemployment    0
IsHoliday       0
dtype: int64

In [22]:
# ==========================
# Duplicate Check
# ==========================

print("Train Duplicates :", train.duplicated().sum())

print("Features Duplicates :", features.duplicated().sum())

print("Stores Duplicates :", stores.duplicated().sum())

Train Duplicates : 0
Features Duplicates : 0
Stores Duplicates : 0

In [23]:
# ==========================
# Date Conversion
# ==========================

train['Date'] = pd.to_datetime(train['Date'])

features['Date'] = pd.to_datetime(features['Date'])

print(train.dtypes)

Store                    int64
Dept                     int64
Date            datetime64[ns]
Weekly_Sales           float64
IsHoliday                 bool
dtype: object

In [24]:
# ==========================
# Merge Train and Features
# ==========================

merged_df = pd.merge(
    train,
    features,
    on=['Store', 'Date', 'IsHoliday'],
    how='left'
)

merged_df.head()

,Store,Dept,Date,Weekly_Sales,IsHoliday,Temperature,Fuel_Price,MarkDown1,MarkDown2,MarkDown3,MarkDown4,MarkDown5,CPI,Unemployment
0,1,1,2010-02-05,24924.50,False,42.31,2.572,0.0,0.0,0.0,0.0,0.0,211.096358,8.106
1,1,1,2010-02-12,46039.49,True,38.51,2.548,0.0,0.0,0.0,0.0,0.0,211.242170,8.106
2,1,1,2010-02-19,41595.55,False,39.93,2.514,0.0,0.0,0.0,0.0,0.0,211.289143,8.106
3,1,1,2010-02-26,19403.54,False,46.63,2.561,0.0,0.0,0.0,0.0,0.0,211.319643,8.106
4,1,1,2010-03-05,21827.90,False,46.50,2.625,0.0,0.0,0.0,0.0,0.0,211.350143,8.106

In [25]:
# ==========================
# Merge Stores
# ==========================

merged_df = pd.merge(
    merged_df,
    stores,
    on='Store',
    how='left'
)

merged_df.head()

,Store,Dept,Date,Weekly_Sales,IsHoliday,Temperature,Fuel_Price,MarkDown1,MarkDown2,MarkDown3,MarkDown4,MarkDown5,CPI,Unemployment,Type,Size
0,1,1,2010-02-05,24924.50,False,42.31,2.572,0.0,0.0,0.0,0.0,0.0,211.096358,8.106,A,151315
1,1,1,2010-02-12,46039.49,True,38.51,2.548,0.0,0.0,0.0,0.0,0.0,211.242170,8.106,A,151315
2,1,1,2010-02-19,41595.55,False,39.93,2.514,0.0,0.0,0.0,0.0,0.0,211.289143,8.106,A,151315
3,1,1,2010-02-26,19403.54,False,46.63,2.561,0.0,0.0,0.0,0.0,0.0,211.319643,8.106,A,151315
4,1,1,2010-03-05,21827.90,False,46.50,2.625,0.0,0.0,0.0,0.0,0.0,211.350143,8.106,A,151315

In [26]:
# ==========================
# Final Dataset Shape
# ==========================

print(merged_df.shape)

(421570, 16)

In [27]:
# ==========================
# Final Missing Values
# ==========================

merged_df.isnull().sum()

Store           0
Dept            0
Date            0
Weekly_Sales    0
IsHoliday       0
Temperature     0
Fuel_Price      0
MarkDown1       0
MarkDown2       0
MarkDown3       0
MarkDown4       0
MarkDown5       0
CPI             0
Unemployment    0
Type            0
Size            0
dtype: int64

In [28]:
# ==========================
# Date Features
# ==========================

merged_df['Year'] = merged_df['Date'].dt.year

merged_df['Month'] = merged_df['Date'].dt.month

merged_df['Week'] = merged_df['Date'].dt.isocalendar().week

merged_df['Quarter'] = merged_df['Date'].dt.quarter

merged_df['Day'] = merged_df['Date'].dt.day

merged_df.head()

,Store,Dept,Date,Weekly_Sales,IsHoliday,Temperature,Fuel_Price,MarkDown1,MarkDown2,MarkDown3,MarkDown4,MarkDown5,CPI,Unemployment,Type,Size,Year,Month,Week,Quarter,Day
0,1,1,2010-02-05,24924.50,False,42.31,2.572,0.0,0.0,0.0,0.0,0.0,211.096358,8.106,A,151315,2010,2,5,1,5
1,1,1,2010-02-12,46039.49,True,38.51,2.548,0.0,0.0,0.0,0.0,0.0,211.242170,8.106,A,151315,2010,2,6,1,12
2,1,1,2010-02-19,41595.55,False,39.93,2.514,0.0,0.0,0.0,0.0,0.0,211.289143,8.106,A,151315,2010,2,7,1,19
3,1,1,2010-02-26,19403.54,False,46.63,2.561,0.0,0.0,0.0,0.0,0.0,211.319643,8.106,A,151315,2010,2,8,1,26
4,1,1,2010-03-05,21827.90,False,46.50,2.625,0.0,0.0,0.0,0.0,0.0,211.350143,8.106,A,151315,2010,3,9,1,5

In [29]:
# ==========================
# Export Cleaned Dataset
# ==========================

merged_df.to_csv(
    "Walmart_Cleaned_Data.csv",
    index=False
)

print("Dataset Saved Successfully!")

Dataset Saved Successfully!

In [30]:
print(merged_df.head())

print()

print(merged_df.info())

print()

print(merged_df.describe())

   Store  Dept       Date  Weekly_Sales  IsHoliday  Temperature  Fuel_Price  \
0      1     1 2010-02-05      24924.50      False        42.31       2.572
1      1     1 2010-02-12      46039.49       True        38.51       2.548
2      1     1 2010-02-19      41595.55      False        39.93       2.514
3      1     1 2010-02-26      19403.54      False        46.63       2.561
4      1     1 2010-03-05      21827.90      False        46.50       2.625

   MarkDown1  MarkDown2  MarkDown3  MarkDown4  MarkDown5         CPI  \
0        0.0        0.0        0.0        0.0        0.0  211.096358
1        0.0        0.0        0.0        0.0        0.0  211.242170
2        0.0        0.0        0.0        0.0        0.0  211.289143
3        0.0        0.0        0.0        0.0        0.0  211.319643
4        0.0        0.0        0.0        0.0        0.0  211.350143

   Unemployment Type    Size  Year  Month  Week  Quarter  Day
0         8.106    A  151315  2010      2     5        1    5
1         8.106    A  151315  2010      2     6        1   12
2         8.106    A  151315  2010      2     7        1   19
3         8.106    A  151315  2010      2     8        1   26
4         8.106    A  151315  2010      3     9        1    5

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 421570 entries, 0 to 421569
Data columns (total 21 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   Store         421570 non-null  int64
 1   Dept          421570 non-null  int64
 2   Date          421570 non-null  datetime64[ns]
 3   Weekly_Sales  421570 non-null  float64
 4   IsHoliday     421570 non-null  bool
 5   Temperature   421570 non-null  float64
 6   Fuel_Price    421570 non-null  float64
 7   MarkDown1     421570 non-null  float64
 8   MarkDown2     421570 non-null  float64
 9   MarkDown3     421570 non-null  float64
 10  MarkDown4     421570 non-null  float64
 11  MarkDown5     421570 non-null  float64
 12  CPI           421570 non-null  float64
 13  Unemployment  421570 non-null  float64
 14  Type          421570 non-null  object
 15  Size          421570 non-null  int64
 16  Year          421570 non-null  int32
 17  Month         421570 non-null  int32
 18  Week          421570 non-null  UInt32
 19  Quarter       421570 non-null  int32
 20  Day           421570 non-null  int32
dtypes: UInt32(1), bool(1), datetime64[ns](1), float64(10), int32(4), int64(3), object(1)
memory usage: 57.1+ MB
None

               Store           Dept                           Date  \
count  421570.000000  421570.000000                         421570
mean       22.200546      44.260317  2011-06-18 08:30:31.963375104
min         1.000000       1.000000            2010-02-05 00:00:00
25%        11.000000      18.000000            2010-10-08 00:00:00
50%        22.000000      37.000000            2011-06-17 00:00:00
75%        33.000000      74.000000            2012-02-24 00:00:00
max        45.000000      99.000000            2012-10-26 00:00:00
std        12.785297      30.492054                            NaN

        Weekly_Sales    Temperature     Fuel_Price      MarkDown1  \
count  421570.000000  421570.000000  421570.000000  421570.000000
mean    15981.258123      60.090059       3.361027    2590.074819
min     -4988.940000      -2.060000       2.472000       0.000000
25%      2079.650000      46.680000       2.933000       0.000000
50%      7612.030000      62.090000       3.452000       0.000000
75%     20205.852500      74.280000       3.738000    2809.050000
max    693099.360000     100.140000       4.468000   88646.760000
std     22711.183519      18.447931       0.458515    6052.385934

           MarkDown2      MarkDown3      MarkDown4      MarkDown5  \
count  421570.000000  421570.000000  421570.000000  421570.000000
mean      879.974298     468.087665    1083.132268    1662.772385
min      -265.760000     -29.100000       0.000000       0.000000
25%         0.000000       0.000000       0.000000       0.000000
50%         0.000000       0.000000       0.000000       0.000000
75%         2.200000       4.540000     425.290000    2168.040000
max    104519.540000  141630.610000   67474.850000  108519.280000
std      5084.538801    5528.873453    3894.529945    4207.629321

                 CPI   Unemployment           Size           Year  \
count  421570.000000  421570.000000  421570.000000  421570.000000
mean      171.201947       7.960289  136727.915739    2010.968591
min       126.064000       3.879000   34875.000000    2010.000000
25%       132.022667       6.891000   93638.000000    2010.000000
50%       182.318780       7.866000  140167.000000    2011.000000
75%       212.416993       8.572000  202505.000000    2012.000000
max       227.232807      14.313000  219622.000000    2012.000000
std        39.159276       1.863296   60980.583328       0.796876

               Month       Week        Quarter            Day
count  421570.000000   421570.0  421570.000000  421570.000000
mean        6.449510  25.826762       2.482767      15.673131
min         1.000000        1.0       1.000000       1.000000
25%         4.000000       14.0       2.000000       8.000000
50%         6.000000       26.0       2.000000      16.000000
75%         9.000000       38.0       3.000000      23.000000
max        12.000000       52.0       4.000000      31.000000
std         3.243217  14.151887       1.071341       8.753549